//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGE.Util.Correo {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Formatos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formatos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGE.Util.Correo.Formatos", typeof(Formatos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot; style=&quot;border: 1px solid #ebccd1; border-collapse: collapse; color:#ffffff; font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;#a94442&quot; style=&quot;padding: 30px 0 30px 0; font-size: 28px; font-weight: bold;&quot;&gt;
        ///            #TITULO#
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr #ACLARACION#&gt;
        ///        &lt;td bgcolor=&quot;#a94442&quot; style=&quot;padding: 0px 30px 30px 30px; font-size: 14px;&quot;&gt;
        ///            &lt;strong&gt;IMPORTANTE: &lt;/strong&gt;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot; style=&quot;border: 1px solid #d6e9c6; border-collapse: collapse; color:#ffffff; font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;#3c763d&quot; style=&quot;padding: 30px 0 30px 0; font-size: 28px; font-weight: bold;&quot;&gt;
        ///            #TITULO#
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr #ACLARACION#&gt;
        ///        &lt;td bgcolor=&quot;#3c763d&quot; style=&quot;padding: 0px 30px 30px 30px; font-size: 14px;&quot;&gt;
        ///            &lt;strong&gt;IMPORTANTE: &lt;/strong&gt;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Exito {
            get {
                return ResourceManager.GetString("Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot; style=&quot;border: 1px solid #bce8f1; border-collapse: collapse; color:#ffffff; font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;#31708f&quot; style=&quot;padding: 30px 0 30px 0; font-size: 28px; font-weight: bold;&quot;&gt;
        ///            #TITULO#
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr #ACLARACION#&gt;
        ///        &lt;td bgcolor=&quot;#31708f&quot; style=&quot;padding: 0px 30px 30px 30px; font-size: 14px;&quot;&gt;
        ///            &lt;strong&gt;IMPORTANTE: &lt;/strong&gt;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot; style=&quot;border: 1px solid #faebcc; border-collapse: collapse; color:#ffffff; font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;center&quot; bgcolor=&quot;#8a6d3b&quot; style=&quot;padding: 30px 0 30px 0; font-size: 28px; font-weight: bold;&quot;&gt;
        ///            #TITULO#
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr #ACLARACION#&gt;
        ///        &lt;td bgcolor=&quot;#8a6d3b&quot; style=&quot;padding: 0px 30px 30px 30px; font-size: 14px;&quot;&gt;
        ///            &lt;strong&gt;IMPORTANTE: &lt;/strong&gt;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Precaucion {
            get {
                return ResourceManager.GetString("Precaucion", resourceCulture);
            }
        }
    }
}
